#!/usr/bin/env python3
"""
svg_to_ufo.py - Convert per-glyph SVG files into a UFO master and a
DesignSpace document suitable for fontmake / gftools builder.

Pipeline
--------
  sources/<Family>/svg/**/*.svg
        │
        ▼  (this script)
  sources/<Family>/ufo/<Weight>.ufo/
  sources/<Family>/<Family>.designspace
        │
        ▼  (gftools builder / fontmake)
  fonts/<Family>/…

SVG coordinate assumptions
--------------------------
  • Artboard is a square of side ``svg_ref_size`` (default 1000).
  • Y = 0  ->  top of capital (cap-height in font coords).
  • Y = svg_ref_size -> baseline (y = 0 in font coords).
  • Descenders extending below baseline are expected to have
    Y > svg_ref_size in their SVG artboard.

Coordinate transform
--------------------
  scale  = cap_height / svg_ref_size
  x_font = x_svg * scale
  y_font = cap_height - y_svg * scale

Usage
-----
  python tools/python/svg_to_ufo.py sources/OctalFont-Titan
  python tools/python/svg_to_ufo.py sources/OctalFont-Titan --weight Regular
  python tools/python/svg_to_ufo.py sources/OctalFont-Titan --dry-run
"""

from __future__ import annotations

import argparse
import math
import re
import sys
import unicodedata
from pathlib import Path
from typing import Generator, Iterator, List, Optional, Sequence, Tuple
from xml.etree import ElementTree as ET

# ---------------------------------------------------------------------------
# Third-party (all in requirements.txt via fontmake / gftools)
# ---------------------------------------------------------------------------
try:
    import ufoLib2
    import yaml
    from fontTools.designspaceLib import (
        AxisDescriptor,
        DesignSpaceDocument,
        InstanceDescriptor,
        SourceDescriptor,
    )
except ImportError as exc:  # pragma: no cover
    sys.exit(
        f"[svg_to_ufo] Missing dependency: {exc}\n"
        "Run:  octalfont env --setup"
    )

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SVG_NS = "http://www.w3.org/2000/svg"

# Minimal OpenType feature file written into the UFO when none exists.
# Edit sources/<Family>/ufo/<Weight>.ufo/features.fea directly to
# add real kern pairs, ligatures, alternates, etc.
_FEATURES_STUB = """\
# OpenType feature definitions for {family_name}
# Generated by svg_to_ufo.py - edit freely.
#
# References:
#   https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html
#   https://fonts.google.com/knowledge/glossary/feature_file

# Language / script
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn MOL ;
languagesystem cyrl dflt;

# Kerning
# feature kern {
#   pos A V -50;
# } kern;

# Ligatures
# feature liga {
#   sub f i by fi;
# } liga;
"""

# Maps SVG filename stems to (glyph_name, unicode_codepoint).
# Single ASCII chars resolve automatically; the table below handles the rest.
_FILENAME_MAP: dict[str, tuple[str, int]] = {
    # Numerals (Illustrator often exports as digit chars or spelled-out names)
    "0": ("zero",    0x0030),
    "1": ("one",     0x0031),
    "2": ("two",     0x0032),
    "3": ("three",   0x0033),
    "4": ("four",    0x0034),
    "5": ("five",    0x0035),
    "6": ("six",     0x0036),
    "7": ("seven",   0x0037),
    "8": ("eight",   0x0038),
    "9": ("nine",    0x0039),
    # Punctuation - extend as you add SVG files
    "period":       ("period",      0x002E),
    "comma":        ("comma",       0x002C),
    "colon":        ("colon",       0x003A),
    "semicolon":    ("semicolon",   0x003B),
    "exclam":       ("exclam",      0x0021),
    "question":     ("question",    0x003F),
    "hyphen":       ("hyphen",      0x002D),
    "underscore":   ("underscore",  0x005F),
    "slash":        ("slash",       0x002F),
    "backslash":    ("backslash",   0x005C),
    "at":           ("at",          0x0040),
    "ampersand":    ("ampersand",   0x0026),
    "parenleft":    ("parenleft",   0x0028),
    "parenright":   ("parenright",  0x0029),
    "bracketleft":  ("bracketleft", 0x005B),
    "bracketright": ("bracketright",0x005D),
    "braceleft":    ("braceleft",   0x007B),
    "braceright":   ("braceright",  0x007D),
    "quotedbl":     ("quotedbl",    0x0022),
    "quotesingle":  ("quotesingle", 0x0027),
    "grave":        ("grave",       0x0060),
    "asterisk":     ("asterisk",    0x002A),
    "plus":         ("plus",        0x002B),
    "equal":        ("equal",       0x003D),
    "less":         ("less",        0x003C),
    "greater":      ("greater",     0x003E),
    "percent":      ("percent",     0x0025),
    "numbersign":   ("numbersign",  0x0023),
    "dollar":       ("dollar",      0x0024),
    "caret":        ("asciicircum", 0x005E),
    "tilde":        ("asciitilde",  0x007E),
    "pipe":         ("bar",         0x007C),
    "space":        ("space",       0x0020),
}


def _stem_to_glyph(stem: str) -> tuple[str, Optional[int]]:
    """Return (glyph_name, unicode_or_None) for an SVG filename stem."""
    if stem in _FILENAME_MAP:
        return _FILENAME_MAP[stem]

    # Single printable ASCII character (A-Z, a-z, etc.)
    if len(stem) == 1 and stem.isprintable():
        cp = ord(stem)
        # Derive AGLFN-compatible name from Unicode character name
        try:
            uname = unicodedata.name(stem).lower().replace(" ", "")
        except ValueError:
            uname = stem
        # For plain letters just use the letter itself as name
        if stem.isalpha():
            return stem, cp
        return uname, cp

    # Unknown / ligature / etc. -> no unicode assignment
    return stem, None


# ---------------------------------------------------------------------------
# SVG path parser
# ---------------------------------------------------------------------------
# Tokenises the `d` attribute and drives a ufoLib2 PointPen.
# Supports: M m L l H h V v C c S s Q q T t A a Z z
# For arc commands (A/a) a cubic-bezier approximation is used.
# ---------------------------------------------------------------------------

_PATH_TOKEN = re.compile(
    r"([MmLlHhVvCcSsQqTtAaZz])|([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)"
)


def _tokenize(d: str) -> Iterator[str]:
    for m in _PATH_TOKEN.finditer(d):
        yield m.group(0)


def _numbers(tokens: Iterator[str], n: int) -> List[float]:
    result: List[float] = []
    while len(result) < n:
        t = next(tokens)
        if t.lstrip("+-").replace(".", "", 1).replace("e", "", 1).replace("E", "", 1).replace("+", "", 1).replace("-", "", 1).isdigit() or re.fullmatch(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?", t):
            result.append(float(t))
    return result


def _arc_to_cubics(
    x1: float, y1: float,
    rx: float, ry: float,
    phi_deg: float,
    large_arc: int, sweep: int,
    x2: float, y2: float,
) -> List[Tuple[float, float, float, float, float, float]]:
    """
    Convert SVG arc to a list of cubic bezier segments.
    Returns list of (cx1, cy1, cx2, cy2, ex, ey) tuples.
    Based on the SVG spec conversion algorithm.
    """
    if x1 == x2 and y1 == y2:
        return []
    if rx == 0 or ry == 0:
        return [(x1, y1, x2, y2, x2, y2)]

    phi = math.radians(phi_deg)
    cos_phi = math.cos(phi)
    sin_phi = math.sin(phi)

    dx = (x1 - x2) / 2
    dy = (y1 - y2) / 2
    x1p =  cos_phi * dx + sin_phi * dy
    y1p = -sin_phi * dx + cos_phi * dy

    rx, ry = abs(rx), abs(ry)
    lam = (x1p / rx) ** 2 + (y1p / ry) ** 2
    if lam > 1:
        sq = math.sqrt(lam)
        rx *= sq
        ry *= sq

    num = max(0.0, (rx * ry) ** 2 - (rx * y1p) ** 2 - (ry * x1p) ** 2)
    den = (rx * y1p) ** 2 + (ry * x1p) ** 2
    sq = math.sqrt(num / den) if den else 0
    if large_arc == sweep:
        sq = -sq

    cxp =  sq * rx * y1p / ry
    cyp = -sq * ry * x1p / rx
    cx = cos_phi * cxp - sin_phi * cyp + (x1 + x2) / 2
    cy = sin_phi * cxp + cos_phi * cyp + (y1 + y2) / 2

    def _angle(ux, uy, vx, vy) -> float:
        n = math.sqrt(ux * ux + uy * uy) * math.sqrt(vx * vx + vy * vy)
        if n == 0:
            return 0.0
        cos_a = max(-1.0, min(1.0, (ux * vx + uy * vy) / n))
        a = math.acos(cos_a)
        if ux * vy - uy * vx < 0:
            a = -a
        return a

    theta1 = _angle(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry)
    dtheta = _angle(
        (x1p - cxp) / rx, (y1p - cyp) / ry,
        (-x1p - cxp) / rx, (-y1p - cyp) / ry,
    )
    if not sweep and dtheta > 0:
        dtheta -= 2 * math.pi
    elif sweep and dtheta < 0:
        dtheta += 2 * math.pi

    # Split into at most 4 segments of ≤ 90°
    n_segs = max(1, math.ceil(abs(dtheta) / (math.pi / 2)))
    dt = dtheta / n_segs
    alpha = math.sin(dt) * (math.sqrt(4 + 3 * math.tan(dt / 2) ** 2) - 1) / 3

    cubics: List[Tuple[float, float, float, float, float, float]] = []
    t = theta1
    for _ in range(n_segs):
        cos_t1 = math.cos(t)
        sin_t1 = math.sin(t)
        t += dt
        cos_t2 = math.cos(t)
        sin_t2 = math.sin(t)

        # End point
        ex = cos_phi * rx * cos_t2 - sin_phi * ry * sin_t2 + cx
        ey = sin_phi * rx * cos_t2 + cos_phi * ry * sin_t2 + cy

        # Control points
        dx1 = -rx * cos_phi * sin_t1 - ry * sin_phi * cos_t1
        dy1 = -rx * sin_phi * sin_t1 + ry * cos_phi * cos_t1
        dx2 =  rx * cos_phi * sin_t2 + ry * sin_phi * cos_t2
        dy2 =  rx * sin_phi * sin_t2 - ry * cos_phi * cos_t2

        cp1x = cos_phi * rx * cos_t1 - sin_phi * ry * sin_t1 + cx + alpha * dx1
        cp1y = sin_phi * rx * cos_t1 + cos_phi * ry * sin_t1 + cy + alpha * dy1
        cp2x = ex - alpha * dx2
        cp2y = ey - alpha * dy2

        cubics.append((cp1x, cp1y, cp2x, cp2y, ex, ey))

    return cubics


class _SvgPathToSegments:
    """
    Parse an SVG path `d` string and call ``segment_callback`` for each
    segment.  Segments are yielded as:
      ("moveto",  [(x, y)])
      ("lineto",  [(x, y)])
      ("curveto", [(c1x,c1y), (c2x,c2y), (x, y)])   # cubic
      ("qcurveto",[(c1x,c1y), (x, y)])               # quadratic
      ("closepath", [])
    """

    def __init__(self, d: str):
        self._d = d

    def segments(self) -> Generator:  # type: ignore[type-arg]
        tokens = _tokenize(self._d)
        cmd: Optional[str] = None
        x = y = 0.0          # current point
        start_x = start_y = 0.0  # subpath start
        last_c2x = last_c2y = 0.0  # last cubic control (for S)
        last_q1x = last_q1y = 0.0  # last quad control (for T)
        prev_cmd: Optional[str] = None

        try:
            token = next(tokens)
        except StopIteration:
            return

        while True:
            if re.fullmatch(r"[MmLlHhVvCcSsQqTtAaZz]", token):
                cmd = token
                try:
                    token = next(tokens)
                except StopIteration:
                    token = ""

            if cmd is None:
                break

            def _peek_num(t: str) -> bool:
                return bool(re.fullmatch(
                    r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?", t
                ))

            def _read(n: int) -> List[float]:
                nonlocal token
                nums: List[float] = []
                while len(nums) < n:
                    if not _peek_num(token):
                        raise ValueError(f"Expected number, got {token!r}")
                    nums.append(float(token))
                    try:
                        token = next(tokens)
                    except StopIteration:
                        token = ""
                return nums

            # ---- M/m ----
            if cmd in ("M", "m"):
                vals = _read(2)
                if cmd == "m":
                    x += vals[0]; y += vals[1]
                else:
                    x, y = vals[0], vals[1]
                start_x, start_y = x, y
                yield "moveto", [(x, y)]
                # Subsequent coords are implicit lineto
                cmd = "l" if cmd == "m" else "L"
                prev_cmd = "M"
                continue

            # ---- Z/z ----
            elif cmd in ("Z", "z"):
                yield "closepath", []
                x, y = start_x, start_y
                # *** Do NOT read another token here. ***
                # The top-of-loop already consumed the token that follows Z
                # (storing it in `token`).  Reading again shifts the stream,
                # dropping the subpath-start M and causing spurious closepaths.

            # ---- L/l ----
            elif cmd in ("L", "l"):
                vals = _read(2)
                if cmd == "l":
                    x += vals[0]; y += vals[1]
                else:
                    x, y = vals[0], vals[1]
                yield "lineto", [(x, y)]

            # ---- H/h ----
            elif cmd in ("H", "h"):
                vals = _read(1)
                if cmd == "h":
                    x += vals[0]
                else:
                    x = vals[0]
                yield "lineto", [(x, y)]

            # ---- V/v ----
            elif cmd in ("V", "v"):
                vals = _read(1)
                if cmd == "v":
                    y += vals[0]
                else:
                    y = vals[0]
                yield "lineto", [(x, y)]

            # ---- C/c ----
            elif cmd in ("C", "c"):
                vals = _read(6)
                if cmd == "c":
                    c1x = x + vals[0]; c1y = y + vals[1]
                    c2x = x + vals[2]; c2y = y + vals[3]
                    ex  = x + vals[4]; ey  = y + vals[5]
                else:
                    c1x, c1y, c2x, c2y, ex, ey = vals
                last_c2x, last_c2y = c2x, c2y
                x, y = ex, ey
                yield "curveto", [(c1x, c1y), (c2x, c2y), (x, y)]

            # ---- S/s  (smooth cubic) ----
            elif cmd in ("S", "s"):
                vals = _read(4)
                if cmd == "s":
                    c2x = x + vals[0]; c2y = y + vals[1]
                    ex  = x + vals[2]; ey  = y + vals[3]
                else:
                    c2x, c2y, ex, ey = vals
                # Reflect last control point
                if prev_cmd in ("C", "c", "S", "s"):
                    c1x = 2 * x - last_c2x
                    c1y = 2 * y - last_c2y
                else:
                    c1x, c1y = x, y
                last_c2x, last_c2y = c2x, c2y
                x, y = ex, ey
                yield "curveto", [(c1x, c1y), (c2x, c2y), (x, y)]

            # ---- Q/q  (quadratic) ----
            elif cmd in ("Q", "q"):
                vals = _read(4)
                if cmd == "q":
                    c1x = x + vals[0]; c1y = y + vals[1]
                    ex  = x + vals[2]; ey  = y + vals[3]
                else:
                    c1x, c1y, ex, ey = vals
                last_q1x, last_q1y = c1x, c1y
                x, y = ex, ey
                yield "qcurveto", [(c1x, c1y), (x, y)]

            # ---- T/t  (smooth quadratic) ----
            elif cmd in ("T", "t"):
                vals = _read(2)
                if cmd == "t":
                    ex = x + vals[0]; ey = y + vals[1]
                else:
                    ex, ey = vals
                if prev_cmd in ("Q", "q", "T", "t"):
                    c1x = 2 * x - last_q1x
                    c1y = 2 * y - last_q1y
                else:
                    c1x, c1y = x, y
                last_q1x, last_q1y = c1x, c1y
                x, y = ex, ey
                yield "qcurveto", [(c1x, c1y), (x, y)]

            # ---- A/a  (arc -> cubic) ----
            elif cmd in ("A", "a"):
                vals = _read(7)
                if cmd == "a":
                    ex = x + vals[5]; ey = y + vals[6]
                else:
                    ex, ey = vals[5], vals[6]
                cubics = _arc_to_cubics(
                    x, y,
                    vals[0], vals[1],     # rx, ry
                    vals[2],               # x-rotation
                    int(vals[3]), int(vals[4]),  # large-arc, sweep
                    ex, ey,
                )
                for c1x, c1y, c2x, c2y, px, py in cubics:
                    last_c2x, last_c2y = c2x, c2y
                    yield "curveto", [(c1x, c1y), (c2x, c2y), (px, py)]
                x, y = ex, ey

            else:
                # Unrecognised command - skip token
                try:
                    token = next(tokens)
                except StopIteration:
                    break
                prev_cmd = cmd
                continue

            prev_cmd = cmd
            # Check if next token starts a new command or is a repeating coord
            if not token or not _peek_num(token):
                if not token:
                    break
                # It's the next command; don't call next()
            # else: same command repeats with next set of coords


# ---------------------------------------------------------------------------
# Coordinate transform helper
# ---------------------------------------------------------------------------


class _Transform:
    """
    Converts SVG coordinates -> font units.

    Params
    ------
    cap_height  : cap-height in font units (typically 700)
    svg_ref     : SVG artboard height (typically 1000)
    """

    def __init__(self, cap_height: float, svg_ref: float) -> None:
        self.scale = cap_height / svg_ref
        self.cap_height = cap_height

    def pt(self, sx: float, sy: float) -> tuple[float, float]:
        return (
            round(sx * self.scale, 3),
            round(self.cap_height - sy * self.scale, 3),
        )


# ---------------------------------------------------------------------------
# SVG -> UFO glyph
# ---------------------------------------------------------------------------


def _points_attr_to_path(points_str: str, close: bool) -> str:
    """
    Convert a <polygon>/<polyline> ``points`` attribute value into an SVG
    path ``d`` string so the same parser can handle it.

    ``close=True``  -> polygon  (implicit Z at end)
    ``close=False`` -> polyline (open path)
    """
    # points are whitespace- or comma-separated numbers
    nums = re.split(r"[\s,]+", points_str.strip())
    nums = [n for n in nums if n]  # drop empty strings
    if len(nums) < 4 or len(nums) % 2 != 0:
        return ""  # degenerate – skip
    coords = [float(n) for n in nums]
    pairs = [(coords[i], coords[i + 1]) for i in range(0, len(coords), 2)]
    d = "M {},{}".format(pairs[0][0], pairs[0][1])
    for px, py in pairs[1:]:
        d += " L {},{}".format(px, py)
    if close:
        d += " Z"
    return d


def _load_svg_paths(path: Path) -> tuple[float, list[str]]:
    """
    Parse an SVG file and return (viewbox_width, list_of_path_d_strings).
    Handles <path>, <polygon>, and <polyline> elements.
    Falls back to width attribute if viewBox is absent.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    # Strip namespace prefix if present
    tag = root.tag.replace(f"{{{SVG_NS}}}", "")
    if tag != "svg":
        raise ValueError(f"Root element is not <svg>: {root.tag}")

    viewbox_w = 1000.0
    vb = root.get("viewBox")
    if vb:
        parts = vb.split()
        if len(parts) == 4:
            viewbox_w = float(parts[2])
    elif root.get("width"):
        viewbox_w = float(root.get("width", "1000").rstrip("px"))

    ds: list[str] = []
    for elem in root.iter():
        local = elem.tag.replace(f"{{{SVG_NS}}}", "")

        if local == "path":
            d = elem.get("d", "").strip()
            if d:
                ds.append(d)

        elif local == "polygon":
            pts = elem.get("points", "").strip()
            if pts:
                d = _points_attr_to_path(pts, close=True)
                if d:
                    ds.append(d)

        elif local == "polyline":
            pts = elem.get("points", "").strip()
            if pts:
                # Font glyph outlines are always closed filled shapes.
                # Illustrator may export a closed shape as <polyline> without
                # repeating the first point - close it explicitly.
                d = _points_attr_to_path(pts, close=True)
                if d:
                    ds.append(d)

    return viewbox_w, ds


def _svg_to_glyph(
    svg_path: Path,
    glyph: "ufoLib2.objects.Glyph",
    transform: _Transform,
    advance_width: Optional[float] = None,
) -> None:
    """Parse SVG and draw contours into *glyph* using its point pen."""
    viewbox_w, path_data = _load_svg_paths(svg_path)
    pen = glyph.getPointPen()

    if advance_width is None:
        glyph.width = round(viewbox_w * transform.scale)
    else:
        glyph.width = round(advance_width)

    for d in path_data:
        parser = _SvgPathToSegments(d)

        # ------------------------------------------------------------------
        # Collect sub-path points before emitting, so we know if it's closed
        # PointPen rules:
        #   Closed contour -> no "move" point; first point has a real segmentType
        #   Open contour   -> first point has segmentType="move"
        # ------------------------------------------------------------------
        subpath_pts: list[tuple[float, float, Optional[str]]] = []
        # (x, y, segmentType)  where segmentType=None means off-curve

        closed = False
        start_xy: tuple[float, float] = (0.0, 0.0)

        def _flush(closed_contour: bool) -> None:
            if not subpath_pts:
                return
            pen.beginPath()
            for ix, (px, py, st) in enumerate(subpath_pts):
                if ix == 0 and not closed_contour:
                    pen.addPoint((px, py), segmentType="move")
                else:
                    pen.addPoint((px, py), segmentType=st)
            pen.endPath()

        for seg_type, pts in parser.segments():
            if seg_type == "moveto":
                # flush previous sub-path as open (Z would have already flushed)
                if subpath_pts:
                    _flush(False)
                    subpath_pts = []
                fx, fy = transform.pt(*pts[0])
                start_xy = (fx, fy)
                subpath_pts = [(fx, fy, "line")]   # placeholder; open=move, closed=line
                closed = False

            elif seg_type == "lineto":
                if not subpath_pts:
                    continue
                fx, fy = transform.pt(*pts[0])
                subpath_pts.append((fx, fy, "line"))

            elif seg_type == "curveto":
                if not subpath_pts:
                    continue
                (c1x, c1y), (c2x, c2y), (ex, ey) = [
                    transform.pt(*p) for p in pts
                ]
                subpath_pts.append((c1x, c1y, None))    # off-curve
                subpath_pts.append((c2x, c2y, None))    # off-curve
                subpath_pts.append((ex, ey, "curve"))

            elif seg_type == "qcurveto":
                if not subpath_pts:
                    continue
                (c1x, c1y), (ex, ey) = [transform.pt(*p) for p in pts]
                subpath_pts.append((c1x, c1y, None))
                subpath_pts.append((ex, ey, "qcurve"))

            elif seg_type == "closepath":
                # Remove duplicate closing point if the last point equals start
                if subpath_pts:
                    last = subpath_pts[-1]
                    sx, sy = start_xy
                    if abs(last[0] - sx) < 0.5 and abs(last[1] - sy) < 0.5 and last[2] is not None:
                        subpath_pts.pop()
                _flush(True)
                subpath_pts = []
                closed = True

        # Any remaining open sub-path
        if subpath_pts:
            _flush(False)


# ---------------------------------------------------------------------------
# UFO builder
# ---------------------------------------------------------------------------


def build_ufo(
    family_dir: Path,
    weight_name: str,
    metrics: dict,
    dry_run: bool = False,
) -> Path:
    """
    Create a UFO master at
    ``<family_dir>/ufo/<weight_name>.ufo``
    from all SVG files found under ``<family_dir>/svg/``.
    Returns the UFO path.
    """
    svg_root = family_dir / "svg"
    ufo_path = family_dir / "ufo" / f"{weight_name}.ufo"

    # Metrics
    upm        = int(metrics.get("upm",        1000))
    ascender   = int(metrics.get("ascender",    800))
    descender  = int(metrics.get("descender",  -200))
    cap_height = int(metrics.get("cap_height",  700))
    x_height   = int(metrics.get("x_height",   500))
    svg_ref    = float(metrics.get("svg_ref_size", 1000))
    family_raw = metrics.get("family_name", family_dir.name)
    # Remove weight suffix from the style-less family name
    family_name = family_raw.replace("OctalFont-", "OctalFont ")

    transform = _Transform(cap_height=cap_height, svg_ref=svg_ref)

    # Collect SVG files
    svg_files: list[Path] = sorted(svg_root.rglob("*.svg"))
    if not svg_files:
        raise FileNotFoundError(f"No SVG files found under {svg_root}")

    print(f"  Found {len(svg_files)} SVG file(s) under {svg_root}")

    if dry_run:
        for f in svg_files:
            stem = f.stem
            gname, cp = _stem_to_glyph(stem)
            uni = f" U+{cp:04X}" if cp else " (no unicode)"
            print(f"    {f.relative_to(family_dir)}  ->  {gname}{uni}")
        return ufo_path

    # Build UFO
    ufo = ufoLib2.Font()

    # Basic font info
    ufo.info.familyName = family_name
    ufo.info.styleName  = weight_name
    ufo.info.unitsPerEm = upm
    ufo.info.capHeight  = cap_height
    ufo.info.xHeight    = x_height
    ufo.info.postscriptUnderlinePosition  = int(metrics.get("underline_position",  -100))
    ufo.info.postscriptUnderlineThickness = int(metrics.get("underline_thickness",   50))

    # Version
    version_str = str(metrics.get("version", "1.000"))
    try:
        major_str, minor_str = version_str.split(".", 1)
        ufo.info.versionMajor = int(major_str)
        ufo.info.versionMinor = int(minor_str)
    except ValueError:
        ufo.info.versionMajor, ufo.info.versionMinor = 1, 0

    # Identity / legal name records
    ufo.info.copyright                   = metrics.get("copyright", "")
    ufo.info.openTypeNameDesigner        = metrics.get("designer", "")
    ufo.info.openTypeNameDesignerURL     = metrics.get("designer_url", "")
    ufo.info.openTypeNameManufacturer    = metrics.get("manufacturer", "")
    ufo.info.openTypeNameManufacturerURL = metrics.get("manufacturer_url", "")
    ufo.info.openTypeNameLicense         = metrics.get("license", "")
    ufo.info.openTypeNameLicenseURL      = metrics.get("license_url", "")
    ufo.info.openTypeOS2VendorID         = str(metrics.get("vendor_id", "NONE"))[:4].upper()

    # Embedding / licensing
    # fsType = 0  ->  Installable Embedding (required for OFL / MIT fonts).
    # An empty list encodes the value 0 in ufoLib2.
    ufo.info.openTypeOS2Type = []

    # Vertical metrics
    # sTypo / hhea = line-box ascender/descender from metrics.yaml.
    # Google Fonts requires: hhea.ascender + |hhea.descender| + lineGap >= 1200.
    # USE_TYPO_METRICS (fsSelection bit 7, set by fix_production.py) tells
    # renderers to use sTypo* for line spacing rather than Win values.
    ufo.info.openTypeOS2TypoAscender  = ascender
    ufo.info.openTypeOS2TypoDescender = descender
    ufo.info.openTypeOS2TypoLineGap   = 0
    ufo.info.openTypeHheaAscender     = ascender
    ufo.info.openTypeHheaDescender    = descender
    ufo.info.openTypeHheaLineGap      = 0
    # Win values = actual glyph bounding-box ceiling/floor.
    # Set to cap_height/0 here; fix_production.py recomputes from compiled glyphs.
    ufo.info.openTypeOS2WinAscent     = cap_height
    ufo.info.openTypeOS2WinDescent    = 0
    # Expose ascender/descender also for PS/legacy consumers
    ufo.info.ascender  = ascender
    ufo.info.descender = descender

    # Add a .notdef glyph
    notdef = ufo.newGlyph(".notdef")
    notdef.width = round(cap_height * 0.6)
    pen = notdef.getPointPen()
    pen.beginPath()
    w = notdef.width
    h = cap_height
    m = round(w * 0.1)  # margin
    t = round(w * 0.08) # stroke thickness
    pen.addPoint((m, 0), segmentType="line")
    pen.addPoint((w - m, 0), segmentType="line")
    pen.addPoint((w - m, h), segmentType="line")
    pen.addPoint((m, h), segmentType="line")
    pen.endPath()
    # Inner rectangle (counter)
    pen.beginPath()
    pen.addPoint((m + t, t), segmentType="line")
    pen.addPoint((m + t, h - t), segmentType="line")
    pen.addPoint((w - m - t, h - t), segmentType="line")
    pen.addPoint((w - m - t, t), segmentType="line")
    pen.endPath()

    # Process SVG files
    skipped = 0
    imported = 0
    for svg_file in svg_files:
        stem = svg_file.stem
        gname, cp = _stem_to_glyph(stem)

        try:
            glyph = ufo.newGlyph(gname)
            if cp is not None:
                glyph.unicodes = [cp]

            _svg_to_glyph(svg_file, glyph, transform)
            imported += 1
            uni_str = f"U+{cp:04X}" if cp else "no-uni"
            print(f"    [{uni_str}]  {gname:20s}  ← {svg_file.relative_to(family_dir)}")

        except Exception as exc:
            print(f"  [WARN] Skipping {svg_file.name}: {exc}", file=sys.stderr)
            skipped += 1

    print(f"  Imported: {imported}  |  Skipped: {skipped}")

    # Add a basic space glyph if not provided by SVGs
    if "space" not in ufo:
        sp = ufo.newGlyph("space")
        sp.unicodes = [0x0020]
        sp.width    = round(cap_height * 0.3)
    # U+00A0 NO-BREAK SPACE - required by fontbakery whitespace_glyphs check.
    # Identical to regular space (same advance, no contours).
    if "nbspace" not in ufo:
        nbsp = ufo.newGlyph("nbspace")
        nbsp.unicodes = [0x00A0]
        nbsp.width    = ufo["space"].width
    # Preserve existing hand-edited features.fea; only write the stub on first run.
    # ufo.features.text is always empty for a freshly created Font() object,
    # so we must check the file on disk rather than the in-memory attribute.
    features_path = ufo_path / "features.fea"
    if features_path.exists():
        ufo.features.text = features_path.read_text(encoding="utf-8")
    else:
        ufo.features.text = _FEATURES_STUB.replace("{family_name}", family_name)
    # Save
    ufo_path.parent.mkdir(parents=True, exist_ok=True)
    ufo.save(str(ufo_path), overwrite=True)
    print(f"  UFO written -> {ufo_path.relative_to(family_dir.parent.parent)}")
    return ufo_path


# ---------------------------------------------------------------------------
# DesignSpace generator
# ---------------------------------------------------------------------------


def build_designspace(
    family_dir: Path,
    ufo_paths: dict[str, Path],  # weight_name -> UFO path
    metrics: dict,
    dry_run: bool = False,
) -> Path:
    """
    Generate a DesignSpace file at ``<family_dir>/<FamilyName>.designspace``.
    For a single master (no variable), creates a minimal static-axis DS.
    For multiple masters keyed by weight value, creates a wght axis.
    """
    family_raw  = metrics.get("family_name", family_dir.name)
    family_name = family_raw.replace("OctalFont-", "OctalFont ")
    ds_path     = family_dir / f"{family_dir.name}.designspace"

    if dry_run:
        print(f"  DesignSpace would be written -> {ds_path.relative_to(family_dir.parent.parent)}")
        return ds_path

    doc = DesignSpaceDocument()

    weight_map: dict[str, int] = {
        "Thin":       100,
        "ExtraLight": 200,
        "Light":      300,
        "Regular":    400,
        "Medium":     500,
        "SemiBold":   600,
        "Bold":       700,
        "ExtraBold":  800,
        "Black":      900,
    }

    if len(ufo_paths) > 1:
        # Variable: add wght axis
        axis = AxisDescriptor()
        axis.tag      = "wght"
        axis.name     = "Weight"
        axis.minimum  = min(weight_map.get(w, 400) for w in ufo_paths)
        axis.default  = weight_map.get("Regular", 400)
        axis.maximum  = max(weight_map.get(w, 400) for w in ufo_paths)
        doc.addAxis(axis)
    else:
        # Static: add a dummy wght axis so fontmake is happy
        axis = AxisDescriptor()
        axis.tag     = "wght"
        axis.name    = "Weight"
        axis.minimum = axis.default = axis.maximum = 400
        doc.addAxis(axis)

    for weight_name, ufo_path in ufo_paths.items():
        src = SourceDescriptor()
        src.filename   = str(ufo_path.relative_to(family_dir))
        src.familyName = family_name
        src.styleName  = weight_name
        src.location   = {"Weight": weight_map.get(weight_name, 400)}
        src.copyInfo   = weight_name == "Regular" or len(ufo_paths) == 1
        doc.addSource(src)

        # Add a matching instance so gftools builder can generate static TTFs
        inst = InstanceDescriptor()
        inst.familyName = family_name
        inst.styleName  = weight_name
        inst.name       = f"{family_name} {weight_name}"
        inst.location   = {"Weight": weight_map.get(weight_name, 400)}
        inst.filename   = f"instances/{family_name.replace(' ', '')}-{weight_name}.ufo"
        doc.addInstance(inst)

    doc.write(str(ds_path))
    print(f"  DesignSpace written -> {ds_path.relative_to(family_dir.parent.parent)}")
    return ds_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_metrics(family_dir: Path) -> dict:
    metrics_file = family_dir / "metrics.yaml"
    if not metrics_file.exists():
        print(f"  [INFO] metrics.yaml not found, using defaults.")
        return {}
    with metrics_file.open() as fh:
        return yaml.safe_load(fh) or {}


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert per-glyph SVG files into a UFO master + DesignSpace.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "family_dir",
        type=Path,
        help="Path to the family source directory (e.g. sources/OctalFont-Titan)",
    )
    parser.add_argument(
        "--weight",
        default="Regular",
        help="Weight name for the UFO master (default: Regular)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be done without writing any files",
    )
    args = parser.parse_args(argv)

    family_dir: Path = args.family_dir.resolve()
    if not family_dir.is_dir():
        print(f"[ERROR] Family directory not found: {family_dir}", file=sys.stderr)
        return 1

    print(f"\n[svg_to_ufo] Family: {family_dir.name}")
    print(f"  Weight:  {args.weight}")
    if args.dry_run:
        print("  Mode:    DRY RUN (no files will be written)\n")

    metrics = _load_metrics(family_dir)
    metrics.setdefault("family_name", family_dir.name)

    try:
        ufo_path = build_ufo(
            family_dir=family_dir,
            weight_name=args.weight,
            metrics=metrics,
            dry_run=args.dry_run,
        )
        build_designspace(
            family_dir=family_dir,
            ufo_paths={args.weight: ufo_path},
            metrics=metrics,
            dry_run=args.dry_run,
        )
    except FileNotFoundError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        import traceback
        print(f"[ERROR] Unexpected error: {exc}", file=sys.stderr)
        traceback.print_exc()
        return 1

    if not args.dry_run:
        print("\n[svg_to_ufo] Done.\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
