"""Package-wide constants for svg_to_ufo."""

from __future__ import annotations


# W3C SVG namespace URI.
SVG_NS: str = "http://www.w3.org/2000/svg"

# Canonical weight names in lightest-to-heaviest order.
KNOWN_WEIGHTS: tuple[str, ...] = (
    "Thin",
    "ExtraLight",
    "Light",
    "Regular",
    "Medium",
    "SemiBold",
    "Bold",
    "ExtraBold",
    "Black",
)

# Maps each weight name to its wght-axis design value.
WEIGHT_MAP: dict[str, int] = {
    "Thin":       100,
    "ExtraLight": 200,
    "Light":      300,
    "Regular":    400,
    "Medium":     500,
    "SemiBold":   600,
    "Bold":       700,
    "ExtraBold":  800,
    "Black":      900,
}

# Written into features.fea the first time a UFO master is created.
# Subsequent runs preserve the hand-edited file on disk unchanged.
FEATURES_STUB: str = """\
# OpenType feature definitions for {family_name}
# Generated by svg_to_ufo - edit freely.
#
# References:
#   https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html
#   https://fonts.google.com/knowledge/glossary/feature_file

# Language / script
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn MOL ;
languagesystem cyrl dflt;

# Kerning
# feature kern {{
#   pos A V -50;
# }} kern;

# Ligatures
# feature liga {{
#   sub f i by fi;
# }} liga;
"""
